name: example
description: Example for provider_for_redux.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  async_redux: ^2.2.0
  path_provider: ^1.4.4
  provider: ^4.0.1
  http: ^0.12.0+2
  tuple: ^1.0.3
  provider_for_redux:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
