name: provider_for_redux
description: Let's you use Provider with Redux. Uses AsyncRedux, the non-boilerplate version of Redux.
version: 1.1.1
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/provider_for_redux

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  async_redux: any
  path_provider: ^1.4.4
  provider: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
