name: provider_for_redux
description: Let's you use Provider with Redux. Uses AsyncRedux, the non-boilerplate version of Redux (https://pub.dev/packages/async_redux).
version: 1.1.4
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/provider_for_redux

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  async_redux: any
  flutter:
    sdk: flutter
  path_provider: ^1.4.4
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
